//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenToGif.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenToGif.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap aero_arrow {
            get {
                object obj = ResourceManager.GetObject("aero_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Brazil_Flag {
            get {
                object obj = ResourceManager.GetObject("Brazil_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulează.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge cadru.
        /// </summary>
        public static string btnDeleteFrame {
            get {
                return ResourceManager.GetString("btnDeleteFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizat.
        /// </summary>
        public static string btnDone {
            get {
                return ResourceManager.GetString("btnDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuă.
        /// </summary>
        public static string btnRecordPause_Continue {
            get {
                return ResourceManager.GetString("btnRecordPause_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înregistrează.
        /// </summary>
        public static string btnRecordPause_Record {
            get {
                return ResourceManager.GetString("btnRecordPause_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulează.
        /// </summary>
        public static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înapoi la început.
        /// </summary>
        public static string btnUndoAll {
            get {
                return ResourceManager.GetString("btnUndoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înapoi cu un pas.
        /// </summary>
        public static string btnUndoOne {
            get {
                return ResourceManager.GetString("btnUndoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editează cadrele după înregistrare.
        /// </summary>
        public static string CB_AllowEdit {
            get {
                return ResourceManager.GetString("CB_AllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizează versiunea cu stilul Legacy (Restartarea aplicației).
        /// </summary>
        public static string CB_LegacyStyle {
            get {
                return ResourceManager.GetString("CB_LegacyStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gif repetat.
        /// </summary>
        public static string CB_Looped {
            get {
                return ResourceManager.GetString("CB_Looped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizează versiunea cu stilul modern (Restartarea aplicației).
        /// </summary>
        public static string CB_ModernStyle {
            get {
                return ResourceManager.GetString("CB_ModernStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetă fără sfârșit.
        /// </summary>
        public static string CB_RepeatForever {
            get {
                return ResourceManager.GetString("CB_RepeatForever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvează direct pe Desktop.
        /// </summary>
        public static string CB_SaveDesktop {
            get {
                return ResourceManager.GetString("CB_SaveDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arată cursorul.
        /// </summary>
        public static string CB_ShowCursor {
            get {
                return ResourceManager.GetString("CB_ShowCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaugă Cadru.
        /// </summary>
        public static string Con_AddFrame {
            get {
                return ResourceManager.GetString("Con_AddFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplică Efecte....
        /// </summary>
        public static string Con_ApplyFilters {
            get {
                return ResourceManager.GetString("Con_ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estompare.
        /// </summary>
        public static string Con_Blur {
            get {
                return ResourceManager.GetString("Con_Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termină.
        /// </summary>
        public static string Con_Cancel {
            get {
                return ResourceManager.GetString("Con_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taie tot....
        /// </summary>
        public static string Con_CropAll {
            get {
                return ResourceManager.GetString("Con_CropAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge acest cadru.
        /// </summary>
        public static string Con_DeleteThis {
            get {
                return ResourceManager.GetString("Con_DeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizat.
        /// </summary>
        public static string Con_Done {
            get {
                return ResourceManager.GetString("Con_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editează Cadrul.
        /// </summary>
        public static string Con_EditFrame {
            get {
                return ResourceManager.GetString("Con_EditFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportează Cadrul....
        /// </summary>
        public static string Con_ExportFrame {
            get {
                return ResourceManager.GetString("Con_ExportFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixelează.
        /// </summary>
        public static string Con_Filters_Pixelate {
            get {
                return ResourceManager.GetString("Con_Filters_Pixelate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrează totul.
        /// </summary>
        public static string Con_FiltersAll {
            get {
                return ResourceManager.GetString("Con_FiltersAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scală Gri.
        /// </summary>
        public static string Con_FiltersGray {
            get {
                return ResourceManager.GetString("Con_FiltersGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrează aceasta.
        /// </summary>
        public static string Con_FiltersThis {
            get {
                return ResourceManager.GetString("Con_FiltersThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport de aspect liber.
        /// </summary>
        public static string Con_FreeAspectRatio {
            get {
                return ResourceManager.GetString("Con_FreeAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagine.
        /// </summary>
        public static string Con_Image {
            get {
                return ResourceManager.GetString("Con_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetează.
        /// </summary>
        public static string Con_Reset {
            get {
                return ResourceManager.GetString("Con_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetează dimensiunea.
        /// </summary>
        public static string Con_ResetSize {
            get {
                return ResourceManager.GetString("Con_ResetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redimensionează totul....
        /// </summary>
        public static string Con_ResizeAll {
            get {
                return ResourceManager.GetString("Con_ResizeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Întoarce ordinea.
        /// </summary>
        public static string Con_Revert {
            get {
                return ResourceManager.GetString("Con_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoyo.
        /// </summary>
        public static string Con_Yoyo {
            get {
                return ResourceManager.GetString("Con_Yoyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge totul după aceasta &gt;&gt;.
        /// </summary>
        public static string Context_DelAfter {
            get {
                return ResourceManager.GetString("Context_DelAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Șterge totul înainte de aceasta.
        /// </summary>
        public static string Context_DelBefore {
            get {
                return ResourceManager.GetString("Context_DelBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deschide o imagine pentru a o introduce.
        /// </summary>
        public static string Dialog_OpenImage {
            get {
                return ResourceManager.GetString("Dialog_OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gear_17 {
            get {
                object obj = ResourceManager.GetObject("Gear_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Image_17 {
            get {
                object obj = ResourceManager.GetObject("Image_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Info_17Blue {
            get {
                object obj = ResourceManager.GetObject("Info_17Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai bine.
        /// </summary>
        public static string Label_Better {
            get {
                return ResourceManager.GetString("Label_Better", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprimarea:.
        /// </summary>
        public static string Label_Compression {
            get {
                return ResourceManager.GetString("Label_Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai rapid.
        /// </summary>
        public static string Label_Fast {
            get {
                return ResourceManager.GetString("Label_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setări Gif:.
        /// </summary>
        public static string Label_GifSettings {
            get {
                return ResourceManager.GetString("Label_GifSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scurtături:.
        /// </summary>
        public static string Label_Hotkeys {
            get {
                return ResourceManager.GetString("Label_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înregistrează/Pauza:.
        /// </summary>
        public static string Label_RecordPause {
            get {
                return ResourceManager.GetString("Label_RecordPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetă contorul.
        /// </summary>
        public static string Label_RepeatCount {
            get {
                return ResourceManager.GetString("Label_RepeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensiune.
        /// </summary>
        public static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai Încet.
        /// </summary>
        public static string Label_Slow {
            get {
                return ResourceManager.GetString("Label_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprește:.
        /// </summary>
        public static string Label_Stop {
            get {
                return ResourceManager.GetString("Label_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setări rapide(Salvat între sesiuni):.
        /// </summary>
        public static string Label_Title_AppSettings {
            get {
                return ResourceManager.GetString("Label_Title_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mult mai rău.
        /// </summary>
        public static string Label_Worst {
            get {
                return ResourceManager.GetString("Label_Worst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MaximizeMinus {
            get {
                object obj = ResourceManager.GetObject("MaximizeMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MaximizePlus {
            get {
                object obj = ResourceManager.GetObject("MaximizePlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Minimize {
            get {
                object obj = ResourceManager.GetObject("Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectează intensitatea estompării.
        /// </summary>
        public static string Msg_BlurIntense {
            get {
                return ResourceManager.GetString("Msg_BlurIntense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exportat....
        /// </summary>
        public static string Msg_Exported {
            get {
                return ResourceManager.GetString("Msg_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusul exportării.
        /// </summary>
        public static string Msg_ExportedTitle {
            get {
                return ResourceManager.GetString("Msg_ExportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadru.
        /// </summary>
        public static string Msg_Frame {
            get {
                return ResourceManager.GetString("Msg_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectează dimensiunea pixelului.
        /// </summary>
        public static string Msg_PixelSize {
            get {
                return ResourceManager.GetString("Msg_PixelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu puteți șterge ultimul cadru..
        /// </summary>
        public static string MsgBox_Message_CantDelete {
            get {
                return ResourceManager.GetString("MsgBox_Message_CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numărul minim de cadre.
        /// </summary>
        public static string MsgBox_Title_CantDelete {
            get {
                return ResourceManager.GetString("MsgBox_Title_CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauză.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pause_17Blue {
            get {
                object obj = ResourceManager.GetObject("Pause_17Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Play_17Green {
            get {
                object obj = ResourceManager.GetObject("Play_17Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codificare GIF preferențiată.
        /// </summary>
        public static string Radio_CustomEncoding {
            get {
                return ResourceManager.GetString("Radio_CustomEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codificare paint.NET.
        /// </summary>
        public static string Radio_PaintEncoding {
            get {
                return ResourceManager.GetString("Radio_PaintEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Separator {
            get {
                object obj = ResourceManager.GetObject("Separator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animație.
        /// </summary>
        public static string SFDialog_Filename {
            get {
                return ResourceManager.GetString("SFDialog_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alege destinația.
        /// </summary>
        public static string SFDialog_Title {
            get {
                return ResourceManager.GetString("SFDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Stop_17Red {
            get {
                object obj = ResourceManager.GetObject("Stop_17Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif (2 secunde rămase).
        /// </summary>
        public static string Title_2SecToGo {
            get {
                return ResourceManager.GetString("Title_2SecToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taie.
        /// </summary>
        public static string Title_Crop {
            get {
                return ResourceManager.GetString("Title_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif - Salvează instantaneu.
        /// </summary>
        public static string Title_Edit_PromptToSave {
            get {
                return ResourceManager.GetString("Title_Edit_PromptToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif - Editor: Cadru .
        /// </summary>
        public static string Title_EditorFrame {
            get {
                return ResourceManager.GetString("Title_EditorFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif ■ (Codificare Finalizată).
        /// </summary>
        public static string Title_EncodingDone {
            get {
                return ResourceManager.GetString("Title_EncodingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre.
        /// </summary>
        public static string Title_Filters {
            get {
                return ResourceManager.GetString("Title_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre - Cadre .
        /// </summary>
        public static string Title_FiltersFrame {
            get {
                return ResourceManager.GetString("Title_FiltersFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redimensionează toate cadrele.
        /// </summary>
        public static string Title_ResizeAllFrames {
            get {
                return ResourceManager.GetString("Title_ResizeAllFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  din .
        /// </summary>
        public static string Title_Thread_out_of {
            get {
                return ResourceManager.GetString("Title_Thread_out_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se procesează (Frame .
        /// </summary>
        public static string Title_Thread_ProcessingFrame {
            get {
                return ResourceManager.GetString("Title_Thread_ProcessingFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif (Pus pe pauză).
        /// </summary>
        public static string TitlePaused {
            get {
                return ResourceManager.GetString("TitlePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif ►.
        /// </summary>
        public static string TitleRecording {
            get {
                return ResourceManager.GetString("TitleRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  secunde rămase).
        /// </summary>
        public static string TitleSecondsToGo {
            get {
                return ResourceManager.GetString("TitleSecondsToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen to Gif ■.
        /// </summary>
        public static string TitleStoped {
            get {
                return ResourceManager.GetString("TitleStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setările aplicației.
        /// </summary>
        public static string Tooltip_AppSettings {
            get {
                return ResourceManager.GetString("Tooltip_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoră toate modificările.
        /// </summary>
        public static string Tooltip_btnCancel {
            get {
                return ResourceManager.GetString("Tooltip_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Șterge cadrul selectat.
        /// </summary>
        public static string Tooltip_btnDeleteFrame {
            get {
                return ResourceManager.GetString("Tooltip_btnDeleteFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvează toate modificările.
        /// </summary>
        public static string Tooltip_btnDone {
            get {
                return ResourceManager.GetString("Tooltip_btnDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setări Gif.
        /// </summary>
        public static string Tooltip_GifSettings {
            get {
                return ResourceManager.GetString("Tooltip_GifSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Înălțime.
        /// </summary>
        public static string Tooltip_Height {
            get {
                return ResourceManager.GetString("Tooltip_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informații.
        /// </summary>
        public static string Tooltip_Info {
            get {
                return ResourceManager.GetString("Tooltip_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadrele capturate pe secundă.
        /// </summary>
        public static string Tooltip_NumFPS {
            get {
                return ResourceManager.GetString("Tooltip_NumFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajutor.
        /// </summary>
        public static string Tooltip_Title {
            get {
                return ResourceManager.GetString("Tooltip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulează toate modificările.
        /// </summary>
        public static string Tooltip_UndoAll {
            get {
                return ResourceManager.GetString("Tooltip_UndoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulează ultima modificare.
        /// </summary>
        public static string Tooltip_UndoOne {
            get {
                return ResourceManager.GetString("Tooltip_UndoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lățime.
        /// </summary>
        public static string Tooltip_Widht {
            get {
                return ResourceManager.GetString("Tooltip_Widht", resourceCulture);
            }
        }
    }
}
