//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenToGif.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FullScreen {
            get {
                return ((bool)(this["FullScreen"]));
            }
            set {
                this["FullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreStart {
            get {
                return ((bool)(this["PreStart"]));
            }
            set {
                this["PreStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCursor {
            get {
                return ((bool)(this["ShowCursor"]));
            }
            set {
                this["ShowCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Snapshot {
            get {
                return ((bool)(this["Snapshot"]));
            }
            set {
                this["Snapshot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StartUp {
            get {
                return ((int)(this["StartUp"]));
            }
            set {
                this["StartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MouseClicks {
            get {
                return ((bool)(this["MouseClicks"]));
            }
            set {
                this["MouseClicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDefaultOutput {
            get {
                return ((bool)(this["UseDefaultOutput"]));
            }
            set {
                this["UseDefaultOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultOutput {
            get {
                return ((string)(this["DefaultOutput"]));
            }
            set {
                this["DefaultOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("auto")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int LastFps {
            get {
                return ((int)(this["LastFps"]));
            }
            set {
                this["LastFps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("518")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("269")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CustomEncoding {
            get {
                return ((bool)(this["CustomEncoding"]));
            }
            set {
                this["CustomEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF32CD32")]
        public global::System.Windows.Media.Color TransparentColor {
            get {
                return ((global::System.Windows.Media.Color)(this["TransparentColor"]));
            }
            set {
                this["TransparentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PaintTransparent {
            get {
                return ((bool)(this["PaintTransparent"]));
            }
            set {
                this["PaintTransparent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Looped {
            get {
                return ((bool)(this["Looped"]));
            }
            set {
                this["Looped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RepeatCount {
            get {
                return ((int)(this["RepeatCount"]));
            }
            set {
                this["RepeatCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RepeatForever {
            get {
                return ((bool)(this["RepeatForever"]));
            }
            set {
                this["RepeatForever"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Quality {
            get {
                return ((int)(this["Quality"]));
            }
            set {
                this["Quality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F7")]
        public global::System.Windows.Forms.Keys StartPauseKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["StartPauseKey"]));
            }
            set {
                this["StartPauseKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F8")]
        public global::System.Windows.Forms.Keys StopKey {
            get {
                return ((global::System.Windows.Forms.Keys)(this["StopKey"]));
            }
            set {
                this["StopKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DetectUnchanged {
            get {
                return ((bool)(this["DetectUnchanged"]));
            }
            set {
                this["DetectUnchanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF5F5F5")]
        public global::System.Windows.Media.Color GridColor1 {
            get {
                return ((global::System.Windows.Media.Color)(this["GridColor1"]));
            }
            set {
                this["GridColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF0F0F0")]
        public global::System.Windows.Media.Color GridColor2 {
            get {
                return ((global::System.Windows.Media.Color)(this["GridColor2"]));
            }
            set {
                this["GridColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,20,20")]
        public global::System.Windows.Rect GridSize {
            get {
                return ((global::System.Windows.Rect)(this["GridSize"]));
            }
            set {
                this["GridSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FixedFrameRate {
            get {
                return ((bool)(this["FixedFrameRate"]));
            }
            set {
                this["FixedFrameRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int SnapshotDefaultDelay {
            get {
                return ((int)(this["SnapshotDefaultDelay"]));
            }
            set {
                this["SnapshotDefaultDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int LastFpsImport {
            get {
                return ((int)(this["LastFpsImport"]));
            }
            set {
                this["LastFpsImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color InsertFillColor {
            get {
                return ((global::System.Windows.Media.Color)(this["InsertFillColor"]));
            }
            set {
                this["InsertFillColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SourceCopy")]
        public global::System.Drawing.CopyPixelOperation CaptureMode {
            get {
                return ((global::System.Drawing.CopyPixelOperation)(this["CaptureMode"]));
            }
            set {
                this["CaptureMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double EditorTop {
            get {
                return ((double)(this["EditorTop"]));
            }
            set {
                this["EditorTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double EditorLeft {
            get {
                return ((double)(this["EditorLeft"]));
            }
            set {
                this["EditorLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double EditorHeight {
            get {
                return ((double)(this["EditorHeight"]));
            }
            set {
                this["EditorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double EditorWidth {
            get {
                return ((double)(this["EditorWidth"]));
            }
            set {
                this["EditorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState EditorWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["EditorWindowState"]));
            }
            set {
                this["EditorWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Text")]
        public string CaptionText {
            get {
                return ((string)(this["CaptionText"]));
            }
            set {
                this["CaptionText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily CaptionFontFamily {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["CaptionFontFamily"]));
            }
            set {
                this["CaptionFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.FontStyle CaptionFontStyle {
            get {
                return ((global::System.Windows.FontStyle)(this["CaptionFontStyle"]));
            }
            set {
                this["CaptionFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bold")]
        public global::System.Windows.FontWeight CaptionFontWeight {
            get {
                return ((global::System.Windows.FontWeight)(this["CaptionFontWeight"]));
            }
            set {
                this["CaptionFontWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double CaptionFontSize {
            get {
                return ((double)(this["CaptionFontSize"]));
            }
            set {
                this["CaptionFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color CaptionFontColor {
            get {
                return ((global::System.Windows.Media.Color)(this["CaptionFontColor"]));
            }
            set {
                this["CaptionFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double CaptionOutlineThickness {
            get {
                return ((double)(this["CaptionOutlineThickness"]));
            }
            set {
                this["CaptionOutlineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color CaptionOutlineColor {
            get {
                return ((global::System.Windows.Media.Color)(this["CaptionOutlineColor"]));
            }
            set {
                this["CaptionOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bottom")]
        public global::System.Windows.VerticalAlignment CaptionVerticalAligment {
            get {
                return ((global::System.Windows.VerticalAlignment)(this["CaptionVerticalAligment"]));
            }
            set {
                this["CaptionVerticalAligment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::System.Windows.HorizontalAlignment CaptionHorizontalAligment {
            get {
                return ((global::System.Windows.HorizontalAlignment)(this["CaptionHorizontalAligment"]));
            }
            set {
                this["CaptionHorizontalAligment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double CaptionMargin {
            get {
                return ((double)(this["CaptionMargin"]));
            }
            set {
                this["CaptionMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Text")]
        public string FreeTextText {
            get {
                return ((string)(this["FreeTextText"]));
            }
            set {
                this["FreeTextText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily FreeTextFontFamily {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["FreeTextFontFamily"]));
            }
            set {
                this["FreeTextFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.FontStyle FreeTextFontStyle {
            get {
                return ((global::System.Windows.FontStyle)(this["FreeTextFontStyle"]));
            }
            set {
                this["FreeTextFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.FontWeight FreeTextFontWeight {
            get {
                return ((global::System.Windows.FontWeight)(this["FreeTextFontWeight"]));
            }
            set {
                this["FreeTextFontWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color FreeTextFontColor {
            get {
                return ((global::System.Windows.Media.Color)(this["FreeTextFontColor"]));
            }
            set {
                this["FreeTextFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double FreeTextFontSize {
            get {
                return ((double)(this["FreeTextFontSize"]));
            }
            set {
                this["FreeTextFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int NewImageWidth {
            get {
                return ((int)(this["NewImageWidth"]));
            }
            set {
                this["NewImageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int NewImageHeight {
            get {
                return ((int)(this["NewImageHeight"]));
            }
            set {
                this["NewImageHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color NewImageColor {
            get {
                return ((global::System.Windows.Media.Color)(this["NewImageColor"]));
            }
            set {
                this["NewImageColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Title")]
        public string TitleFrameText {
            get {
                return ((string)(this["TitleFrameText"]));
            }
            set {
                this["TitleFrameText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily TitleFrameFontFamily {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["TitleFrameFontFamily"]));
            }
            set {
                this["TitleFrameFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.FontStyle TitleFrameFontStyle {
            get {
                return ((global::System.Windows.FontStyle)(this["TitleFrameFontStyle"]));
            }
            set {
                this["TitleFrameFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.FontWeight TitleFrameFontWeight {
            get {
                return ((global::System.Windows.FontWeight)(this["TitleFrameFontWeight"]));
            }
            set {
                this["TitleFrameFontWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color TitleFrameFontColor {
            get {
                return ((global::System.Windows.Media.Color)(this["TitleFrameFontColor"]));
            }
            set {
                this["TitleFrameFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::System.Windows.VerticalAlignment TitleFrameVerticalAligment {
            get {
                return ((global::System.Windows.VerticalAlignment)(this["TitleFrameVerticalAligment"]));
            }
            set {
                this["TitleFrameVerticalAligment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Center")]
        public global::System.Windows.HorizontalAlignment TitleFrameHorizontalAligment {
            get {
                return ((global::System.Windows.HorizontalAlignment)(this["TitleFrameHorizontalAligment"]));
            }
            set {
                this["TitleFrameHorizontalAligment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD7D7D7")]
        public global::System.Windows.Media.Color TitleFrameBackgroundColor {
            get {
                return ((global::System.Windows.Media.Color)(this["TitleFrameBackgroundColor"]));
            }
            set {
                this["TitleFrameBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double TitleFrameFontSize {
            get {
                return ((double)(this["TitleFrameFontSize"]));
            }
            set {
                this["TitleFrameFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TitleFrameMargin {
            get {
                return ((double)(this["TitleFrameMargin"]));
            }
            set {
                this["TitleFrameMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double RecorderTop {
            get {
                return ((double)(this["RecorderTop"]));
            }
            set {
                this["RecorderTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double RecorderLeft {
            get {
                return ((double)(this["RecorderLeft"]));
            }
            set {
                this["RecorderLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatermarkFilePath {
            get {
                return ((string)(this["WatermarkFilePath"]));
            }
            set {
                this["WatermarkFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double WatermarkOpacity {
            get {
                return ((double)(this["WatermarkOpacity"]));
            }
            set {
                this["WatermarkOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double WatermarkSize {
            get {
                return ((double)(this["WatermarkSize"]));
            }
            set {
                this["WatermarkSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bottom")]
        public global::System.Windows.VerticalAlignment WatermarkVerticalAligment {
            get {
                return ((global::System.Windows.VerticalAlignment)(this["WatermarkVerticalAligment"]));
            }
            set {
                this["WatermarkVerticalAligment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::System.Windows.HorizontalAlignment WatermarkHorizontalAligment {
            get {
                return ((global::System.Windows.HorizontalAlignment)(this["WatermarkHorizontalAligment"]));
            }
            set {
                this["WatermarkHorizontalAligment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double WatermarkMargin {
            get {
                return ((double)(this["WatermarkMargin"]));
            }
            set {
                this["WatermarkMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color BorderColor {
            get {
                return ((global::System.Windows.Media.Color)(this["BorderColor"]));
            }
            set {
                this["BorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double BorderLeftThickness {
            get {
                return ((double)(this["BorderLeftThickness"]));
            }
            set {
                this["BorderLeftThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double BorderTopThickness {
            get {
                return ((double)(this["BorderTopThickness"]));
            }
            set {
                this["BorderTopThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double BorderRightThickness {
            get {
                return ((double)(this["BorderRightThickness"]));
            }
            set {
                this["BorderRightThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double BorderBottomThickness {
            get {
                return ((double)(this["BorderBottomThickness"]));
            }
            set {
                this["BorderBottomThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int FreeDrawingPenWidth {
            get {
                return ((int)(this["FreeDrawingPenWidth"]));
            }
            set {
                this["FreeDrawingPenWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int FreeDrawingPenHeight {
            get {
                return ((int)(this["FreeDrawingPenHeight"]));
            }
            set {
                this["FreeDrawingPenHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color FreeDrawingColor {
            get {
                return ((global::System.Windows.Media.Color)(this["FreeDrawingColor"]));
            }
            set {
                this["FreeDrawingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ellipse")]
        public global::System.Windows.Ink.StylusTip FreeDrawingStylusTip {
            get {
                return ((global::System.Windows.Ink.StylusTip)(this["FreeDrawingStylusTip"]));
            }
            set {
                this["FreeDrawingStylusTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FreeDrawingIsHighlighter {
            get {
                return ((bool)(this["FreeDrawingIsHighlighter"]));
            }
            set {
                this["FreeDrawingIsHighlighter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FreeDrawingFitToCurve {
            get {
                return ((bool)(this["FreeDrawingFitToCurve"]));
            }
            set {
                this["FreeDrawingFitToCurve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FreeDrawingEraserWidth {
            get {
                return ((int)(this["FreeDrawingEraserWidth"]));
            }
            set {
                this["FreeDrawingEraserWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FreeDrawingEraserHeight {
            get {
                return ((int)(this["FreeDrawingEraserHeight"]));
            }
            set {
                this["FreeDrawingEraserHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rectangle")]
        public global::System.Windows.Ink.StylusTip FreeDrawingEraserStylusTip {
            get {
                return ((global::System.Windows.Ink.StylusTip)(this["FreeDrawingEraserStylusTip"]));
            }
            set {
                this["FreeDrawingEraserStylusTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditorExtendChrome {
            get {
                return ((bool)(this["EditorExtendChrome"]));
            }
            set {
                this["EditorExtendChrome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66")]
        public int PlaybackOverrideDelay {
            get {
                return ((int)(this["PlaybackOverrideDelay"]));
            }
            set {
                this["PlaybackOverrideDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int PlaybackChangeDelay {
            get {
                return ((int)(this["PlaybackChangeDelay"]));
            }
            set {
                this["PlaybackChangeDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int CinemagraphPenWidth {
            get {
                return ((int)(this["CinemagraphPenWidth"]));
            }
            set {
                this["CinemagraphPenWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int CinemagraphPenHeight {
            get {
                return ((int)(this["CinemagraphPenHeight"]));
            }
            set {
                this["CinemagraphPenHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ellipse")]
        public global::System.Windows.Ink.StylusTip CinemagraphStylusTip {
            get {
                return ((global::System.Windows.Ink.StylusTip)(this["CinemagraphStylusTip"]));
            }
            set {
                this["CinemagraphStylusTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CinemagraphIsHighlighter {
            get {
                return ((bool)(this["CinemagraphIsHighlighter"]));
            }
            set {
                this["CinemagraphIsHighlighter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CinemagraphFitToCurve {
            get {
                return ((bool)(this["CinemagraphFitToCurve"]));
            }
            set {
                this["CinemagraphFitToCurve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int CinemagraphEraserWidth {
            get {
                return ((int)(this["CinemagraphEraserWidth"]));
            }
            set {
                this["CinemagraphEraserWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int CinemagraphEraserHeight {
            get {
                return ((int)(this["CinemagraphEraserHeight"]));
            }
            set {
                this["CinemagraphEraserHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rectangle")]
        public global::System.Windows.Ink.StylusTip CinemagraphEraserStylusTip {
            get {
                return ((global::System.Windows.Ink.StylusTip)(this["CinemagraphEraserStylusTip"]));
            }
            set {
                this["CinemagraphEraserStylusTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#2000FF10")]
        public global::System.Windows.Media.Color CinemagraphColor {
            get {
                return ((global::System.Windows.Media.Color)(this["CinemagraphColor"]));
            }
            set {
                this["CinemagraphColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF00")]
        public global::System.Windows.Media.Color ClickColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ClickColor"]));
            }
            set {
                this["ClickColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int FadeFrameCount {
            get {
                return ((int)(this["FadeFrameCount"]));
            }
            set {
                this["FadeFrameCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int TitleFrameDelay {
            get {
                return ((int)(this["TitleFrameDelay"]));
            }
            set {
                this["TitleFrameDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color BoardColor {
            get {
                return ((global::System.Windows.Media.Color)(this["BoardColor"]));
            }
            set {
                this["BoardColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ellipse")]
        public global::System.Windows.Ink.StylusTip BoardStylusTip {
            get {
                return ((global::System.Windows.Ink.StylusTip)(this["BoardStylusTip"]));
            }
            set {
                this["BoardStylusTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BoardStylusWidth {
            get {
                return ((int)(this["BoardStylusWidth"]));
            }
            set {
                this["BoardStylusWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BoardStylusHeight {
            get {
                return ((int)(this["BoardStylusHeight"]));
            }
            set {
                this["BoardStylusHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BoardIsHighlighter {
            get {
                return ((bool)(this["BoardIsHighlighter"]));
            }
            set {
                this["BoardIsHighlighter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BoardFitToCurve {
            get {
                return ((bool)(this["BoardFitToCurve"]));
            }
            set {
                this["BoardFitToCurve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BoardEraserWidth {
            get {
                return ((int)(this["BoardEraserWidth"]));
            }
            set {
                this["BoardEraserWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BoardEraserHeight {
            get {
                return ((int)(this["BoardEraserHeight"]));
            }
            set {
                this["BoardEraserHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rectangle")]
        public global::System.Windows.Ink.StylusTip BoardEraserStylusTip {
            get {
                return ((global::System.Windows.Ink.StylusTip)(this["BoardEraserStylusTip"]));
            }
            set {
                this["BoardEraserStylusTip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color BoardGridColor1 {
            get {
                return ((global::System.Windows.Media.Color)(this["BoardGridColor1"]));
            }
            set {
                this["BoardGridColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color BoardGridColor2 {
            get {
                return ((global::System.Windows.Media.Color)(this["BoardGridColor2"]));
            }
            set {
                this["BoardGridColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,20,20")]
        public global::System.Windows.Rect BoardGridSize {
            get {
                return ((global::System.Windows.Rect)(this["BoardGridSize"]));
            }
            set {
                this["BoardGridSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color BoardGridBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["BoardGridBackground"]));
            }
            set {
                this["BoardGridBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TransparentCorner {
            get {
                return ((bool)(this["TransparentCorner"]));
            }
            set {
                this["TransparentCorner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-666")]
        public int WatermarkTop {
            get {
                return ((int)(this["WatermarkTop"]));
            }
            set {
                this["WatermarkTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-666")]
        public int WatermarkLeft {
            get {
                return ((int)(this["WatermarkLeft"]));
            }
            set {
                this["WatermarkLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FfmpegLocation {
            get {
                return ((string)(this["FfmpegLocation"]));
            }
            set {
                this["FfmpegLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LatestFilename {
            get {
                return ((string)(this["LatestFilename"]));
            }
            set {
                this["LatestFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int AviQuality {
            get {
                return ((int)(this["AviQuality"]));
            }
            set {
                this["AviQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-mbd rd -flags +mv4+aic -trellis 2 -cmp 2 -subcmp 2 -g 300 -pass 1")]
        public string ExtraParameters {
            get {
                return ((string)(this["ExtraParameters"]));
            }
            set {
                this["ExtraParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int OutputFramerate {
            get {
                return ((int)(this["OutputFramerate"]));
            }
            set {
                this["OutputFramerate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gif")]
        public global::ScreenToGif.Util.Export SaveType {
            get {
                return ((global::ScreenToGif.Util.Export)(this["SaveType"]));
            }
            set {
                this["SaveType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Legacy")]
        public global::ScreenToGif.Util.GifEncoderType GifEncoder {
            get {
                return ((global::ScreenToGif.Util.GifEncoderType)(this["GifEncoder"]));
            }
            set {
                this["GifEncoder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AviStandalone")]
        public global::ScreenToGif.Util.VideoEncoderType VideoEncoder {
            get {
                return ((global::ScreenToGif.Util.VideoEncoderType)(this["VideoEncoder"]));
            }
            set {
                this["VideoEncoder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemporaryFolder {
            get {
                return ((string)(this["TemporaryFolder"]));
            }
            set {
                this["TemporaryFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverwriteOnSave {
            get {
                return ((bool)(this["OverwriteOnSave"]));
            }
            set {
                this["OverwriteOnSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bar")]
        public global::ScreenToGif.Util.ProgressType ProgressType {
            get {
                return ((global::ScreenToGif.Util.ProgressType)(this["ProgressType"]));
            }
            set {
                this["ProgressType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public global::System.Windows.Media.FontFamily ProgressFontFamily {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["ProgressFontFamily"]));
            }
            set {
                this["ProgressFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.FontStyle ProgressFontStyle {
            get {
                return ((global::System.Windows.FontStyle)(this["ProgressFontStyle"]));
            }
            set {
                this["ProgressFontStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.FontWeight ProgressFontWeight {
            get {
                return ((global::System.Windows.FontWeight)(this["ProgressFontWeight"]));
            }
            set {
                this["ProgressFontWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double ProgressFontSize {
            get {
                return ((double)(this["ProgressFontSize"]));
            }
            set {
                this["ProgressFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color ProgressFontColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ProgressFontColor"]));
            }
            set {
                this["ProgressFontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color ProgressColor {
            get {
                return ((global::System.Windows.Media.Color)(this["ProgressColor"]));
            }
            set {
                this["ProgressColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProgressPrecision {
            get {
                return ((int)(this["ProgressPrecision"]));
            }
            set {
                this["ProgressPrecision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double ProgressThickness {
            get {
                return ((double)(this["ProgressThickness"]));
            }
            set {
                this["ProgressThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bottom")]
        public global::System.Windows.VerticalAlignment ProgressVerticalAligment {
            get {
                return ((global::System.Windows.VerticalAlignment)(this["ProgressVerticalAligment"]));
            }
            set {
                this["ProgressVerticalAligment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.HorizontalAlignment ProgressHorizontalAligment {
            get {
                return ((global::System.Windows.HorizontalAlignment)(this["ProgressHorizontalAligment"]));
            }
            set {
                this["ProgressHorizontalAligment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Horizontal")]
        public global::System.Windows.Controls.Orientation ProgressOrientation {
            get {
                return ((global::System.Windows.Controls.Orientation)(this["ProgressOrientation"]));
            }
            set {
                this["ProgressOrientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecorderThinMode {
            get {
                return ((bool)(this["RecorderThinMode"]));
            }
            set {
                this["RecorderThinMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AsyncRecording {
            get {
                return ((bool)(this["AsyncRecording"]));
            }
            set {
                this["AsyncRecording"] = value;
            }
        }
    }
}
