<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ScreenToGif.Linux</RootNamespace>
    <AssemblyName>ScreenToGif.Linux</AssemblyName>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="../ScreenToGif/Resources/Logo.ico" Link="Resources/Logo.ico" />
    <None Include="Resources/screentogif.png" CopyToOutputDirectory="PreserveNewest" />
    <None Include="screentogif.desktop" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Microsoft.Net.Compilers.Toolset">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
