//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenToGif {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenToGif.Resources_pt-BR", typeof(Resources_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar.
        /// </summary>
        internal static string btnDeleteFrame {
            get {
                return ResourceManager.GetString("btnDeleteFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        internal static string btnDone {
            get {
                return ResourceManager.GetString("btnDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string btnRecordPause_Continue {
            get {
                return ResourceManager.GetString("btnRecordPause_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        internal static string btnRecordPause_Record {
            get {
                return ResourceManager.GetString("btnRecordPause_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar.
        /// </summary>
        internal static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer Tudo.
        /// </summary>
        internal static string btnUndoAll {
            get {
                return ResourceManager.GetString("btnUndoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer.
        /// </summary>
        internal static string btnUndoOne {
            get {
                return ResourceManager.GetString("btnUndoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar quadros depois de gravar.
        /// </summary>
        internal static string CB_AllowEdit {
            get {
                return ResourceManager.GetString("CB_AllowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar a janela no estilo Legado (reinicie o app).
        /// </summary>
        internal static string CB_LegacyStyle {
            get {
                return ResourceManager.GetString("CB_LegacyStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gif em loop.
        /// </summary>
        internal static string CB_Looped {
            get {
                return ResourceManager.GetString("CB_Looped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar a janela no estilo Moderno (reinicie o app).
        /// </summary>
        internal static string CB_ModernStyle {
            get {
                return ResourceManager.GetString("CB_ModernStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetir Para Sempre.
        /// </summary>
        internal static string CB_RepeatForever {
            get {
                return ResourceManager.GetString("CB_RepeatForever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar diretamente no Desktop.
        /// </summary>
        internal static string CB_SaveDesktop {
            get {
                return ResourceManager.GetString("CB_SaveDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar Cursor.
        /// </summary>
        internal static string CB_ShowCursor {
            get {
                return ResourceManager.GetString("CB_ShowCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Frame.
        /// </summary>
        internal static string Con_AddFrame {
            get {
                return ResourceManager.GetString("Con_AddFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar Filtros....
        /// </summary>
        internal static string Con_ApplyFilters {
            get {
                return ResourceManager.GetString("Con_ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfocar.
        /// </summary>
        internal static string Con_Blur {
            get {
                return ResourceManager.GetString("Con_Blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Con_Cancel {
            get {
                return ResourceManager.GetString("Con_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recortar Todos....
        /// </summary>
        internal static string Con_CropAll {
            get {
                return ResourceManager.GetString("Con_CropAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar Esse Quadro.
        /// </summary>
        internal static string Con_DeleteThis {
            get {
                return ResourceManager.GetString("Con_DeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        internal static string Con_Done {
            get {
                return ResourceManager.GetString("Con_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Quadro.
        /// </summary>
        internal static string Con_EditFrame {
            get {
                return ResourceManager.GetString("Con_EditFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Quadro....
        /// </summary>
        internal static string Con_ExportFrame {
            get {
                return ResourceManager.GetString("Con_ExportFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixelar.
        /// </summary>
        internal static string Con_Filters_Pixelate {
            get {
                return ResourceManager.GetString("Con_Filters_Pixelate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar p/ Todos.
        /// </summary>
        internal static string Con_FiltersAll {
            get {
                return ResourceManager.GetString("Con_FiltersAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escala de Cinza.
        /// </summary>
        internal static string Con_FiltersGray {
            get {
                return ResourceManager.GetString("Con_FiltersGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar p/ Esse.
        /// </summary>
        internal static string Con_FiltersThis {
            get {
                return ResourceManager.GetString("Con_FiltersThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proporção Livre.
        /// </summary>
        internal static string Con_FreeAspectRatio {
            get {
                return ResourceManager.GetString("Con_FreeAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem.
        /// </summary>
        internal static string Con_Image {
            get {
                return ResourceManager.GetString("Con_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negativo.
        /// </summary>
        internal static string Con_Negative {
            get {
                return ResourceManager.GetString("Con_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pré-visualizar.
        /// </summary>
        internal static string Con_PlayPreview {
            get {
                return ResourceManager.GetString("Con_PlayPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetar.
        /// </summary>
        internal static string Con_Reset {
            get {
                return ResourceManager.GetString("Con_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetar Tamanho.
        /// </summary>
        internal static string Con_ResetSize {
            get {
                return ResourceManager.GetString("Con_ResetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redimensionar Tudo....
        /// </summary>
        internal static string Con_ResizeAll {
            get {
                return ResourceManager.GetString("Con_ResizeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverter Ordem.
        /// </summary>
        internal static string Con_Revert {
            get {
                return ResourceManager.GetString("Con_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sépia.
        /// </summary>
        internal static string Con_Sepia {
            get {
                return ResourceManager.GetString("Con_Sepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar Pré-visualização.
        /// </summary>
        internal static string Con_StopPreview {
            get {
                return ResourceManager.GetString("Con_StopPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparência.
        /// </summary>
        internal static string Con_Transparency {
            get {
                return ResourceManager.GetString("Con_Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Io-io.
        /// </summary>
        internal static string Con_Yoyo {
            get {
                return ResourceManager.GetString("Con_Yoyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar tudo depois disso&gt;&gt;.
        /// </summary>
        internal static string Context_DelAfter {
            get {
                return ResourceManager.GetString("Context_DelAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Deletar tudo antes disso.
        /// </summary>
        internal static string Context_DelBefore {
            get {
                return ResourceManager.GetString("Context_DelBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha uma imagem para inserir.
        /// </summary>
        internal static string Dialog_OpenImage {
            get {
                return ResourceManager.GetString("Dialog_OpenImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melhor.
        /// </summary>
        internal static string Label_Better {
            get {
                return ResourceManager.GetString("Label_Better", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressão:.
        /// </summary>
        internal static string Label_Compression {
            get {
                return ResourceManager.GetString("Label_Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rápido.
        /// </summary>
        internal static string Label_Fast {
            get {
                return ResourceManager.GetString("Label_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações do Gif:.
        /// </summary>
        internal static string Label_GifSettings {
            get {
                return ResourceManager.GetString("Label_GifSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atalhos:.
        /// </summary>
        internal static string Label_Hotkeys {
            get {
                return ResourceManager.GetString("Label_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar/Pausar:.
        /// </summary>
        internal static string Label_RecordPause {
            get {
                return ResourceManager.GetString("Label_RecordPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quant. Repetições.
        /// </summary>
        internal static string Label_RepeatCount {
            get {
                return ResourceManager.GetString("Label_RepeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        internal static string Label_Size {
            get {
                return ResourceManager.GetString("Label_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lento.
        /// </summary>
        internal static string Label_Slow {
            get {
                return ResourceManager.GetString("Label_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar:.
        /// </summary>
        internal static string Label_Stop {
            get {
                return ResourceManager.GetString("Label_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações Rápidas (Salvo entre sessões):.
        /// </summary>
        internal static string Label_Title_AppSettings {
            get {
                return ResourceManager.GetString("Label_Title_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pior.
        /// </summary>
        internal static string Label_Worst {
            get {
                return ResourceManager.GetString("Label_Worst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a Intensidade do Desfoque.
        /// </summary>
        internal static string Msg_BlurIntense {
            get {
                return ResourceManager.GetString("Msg_BlurIntense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  exportado....
        /// </summary>
        internal static string Msg_Exported {
            get {
                return ResourceManager.GetString("Msg_Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado da Exportação.
        /// </summary>
        internal static string Msg_ExportedTitle {
            get {
                return ResourceManager.GetString("Msg_ExportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadro .
        /// </summary>
        internal static string Msg_Frame {
            get {
                return ResourceManager.GetString("Msg_Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o Tamanho do Pixel.
        /// </summary>
        internal static string Msg_PixelSize {
            get {
                return ResourceManager.GetString("Msg_PixelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não pode deletar o último quadro..
        /// </summary>
        internal static string MsgBox_Message_CantDelete {
            get {
                return ResourceManager.GetString("MsgBox_Message_CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade Mínima de Quadros.
        /// </summary>
        internal static string MsgBox_Title_CantDelete {
            get {
                return ResourceManager.GetString("MsgBox_Title_CantDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausar.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codificação GIF Personalizada.
        /// </summary>
        internal static string Radio_CustomEncoding {
            get {
                return ResourceManager.GetString("Radio_CustomEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codificação paint.NET.
        /// </summary>
        internal static string Radio_PaintEncoding {
            get {
                return ResourceManager.GetString("Radio_PaintEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animação.
        /// </summary>
        internal static string SFDialog_Filename {
            get {
                return ResourceManager.GetString("SFDialog_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o Destino.
        /// </summary>
        internal static string SFDialog_Title {
            get {
                return ResourceManager.GetString("SFDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif (2 segundos restantes).
        /// </summary>
        internal static string Title_2SecToGo {
            get {
                return ResourceManager.GetString("Title_2SecToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recortar.
        /// </summary>
        internal static string Title_Crop {
            get {
                return ResourceManager.GetString("Title_Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif - Salvar.
        /// </summary>
        internal static string Title_Edit_PromptToSave {
            get {
                return ResourceManager.GetString("Title_Edit_PromptToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif - Editor: Quadro .
        /// </summary>
        internal static string Title_EditorFrame {
            get {
                return ResourceManager.GetString("Title_EditorFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif ■ (Codificação Concluída).
        /// </summary>
        internal static string Title_EncodingDone {
            get {
                return ResourceManager.GetString("Title_EncodingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        internal static string Title_Filters {
            get {
                return ResourceManager.GetString("Title_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros - Quadro .
        /// </summary>
        internal static string Title_FiltersFrame {
            get {
                return ResourceManager.GetString("Title_FiltersFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redimensionar Todos os Frames.
        /// </summary>
        internal static string Title_ResizeAllFrames {
            get {
                return ResourceManager.GetString("Title_ResizeAllFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  de .
        /// </summary>
        internal static string Title_Thread_out_of {
            get {
                return ResourceManager.GetString("Title_Thread_out_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando (Quadro .
        /// </summary>
        internal static string Title_Thread_ProcessingFrame {
            get {
                return ResourceManager.GetString("Title_Thread_ProcessingFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif (Pausado).
        /// </summary>
        internal static string TitlePaused {
            get {
                return ResourceManager.GetString("TitlePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen To Gif ►.
        /// </summary>
        internal static string TitleRecording {
            get {
                return ResourceManager.GetString("TitleRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  segundos restantes).
        /// </summary>
        internal static string TitleSecondsToGo {
            get {
                return ResourceManager.GetString("TitleSecondsToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen to Gif ■.
        /// </summary>
        internal static string TitleStoped {
            get {
                return ResourceManager.GetString("TitleStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações do Aplicativo.
        /// </summary>
        internal static string Tooltip_AppSettings {
            get {
                return ResourceManager.GetString("Tooltip_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorar todas as alterações.
        /// </summary>
        internal static string Tooltip_btnCancel {
            get {
                return ResourceManager.GetString("Tooltip_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar o quadro selecionado.
        /// </summary>
        internal static string Tooltip_btnDeleteFrame {
            get {
                return ResourceManager.GetString("Tooltip_btnDeleteFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar todas as alterações.
        /// </summary>
        internal static string Tooltip_btnDone {
            get {
                return ResourceManager.GetString("Tooltip_btnDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique com o botão direito para selecionar os filtros..
        /// </summary>
        internal static string Tooltip_FiltersPage {
            get {
                return ResourceManager.GetString("Tooltip_FiltersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações do GIF.
        /// </summary>
        internal static string Tooltip_GifSettings {
            get {
                return ResourceManager.GetString("Tooltip_GifSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura.
        /// </summary>
        internal static string Tooltip_Height {
            get {
                return ResourceManager.GetString("Tooltip_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        internal static string Tooltip_Info {
            get {
                return ResourceManager.GetString("Tooltip_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os quadros capturados por segundo.
        /// </summary>
        internal static string Tooltip_NumFPS {
            get {
                return ResourceManager.GetString("Tooltip_NumFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajuda.
        /// </summary>
        internal static string Tooltip_Title {
            get {
                return ResourceManager.GetString("Tooltip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverter todas as alterações.
        /// </summary>
        internal static string Tooltip_UndoAll {
            get {
                return ResourceManager.GetString("Tooltip_UndoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desfazer a última alteração.
        /// </summary>
        internal static string Tooltip_UndoOne {
            get {
                return ResourceManager.GetString("Tooltip_UndoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largura.
        /// </summary>
        internal static string Tooltip_Widht {
            get {
                return ResourceManager.GetString("Tooltip_Widht", resourceCulture);
            }
        }
    }
}
