name: WinGet • Releases
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: NickeManarin.ScreenToGif
          installers-regex: '.*[^Light].Setup.*.msi$'
          token: ${{ secrets.WINGET_TOKEN }}
